baseURL = "https://m4nj4r0.github.io/blog/"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Manjaro"

[params]
  avatarURL = "/images/avatar.png"

  description = "Posts about binary exploitation."

  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 4

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'
